name: ageProgression
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - aom=3.5.0
  - appdirs=1.4.4
  - appnope=0.1.3
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - contourpy=1.0.7
  - cryptography=39.0.1
  - cycler=0.11.0
  - debugpy=1.6.6
  - decorator=5.1.1
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=5.1.2
  - filelock=3.9.0
  - flit-core=3.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.2
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - graphite2=1.3.13
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - icu=70.1
  - idna=3.4
  - imageio=2.26.0
  - importlib-metadata=6.1.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.1.0
  - importlib_resources=5.12.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.0
  - ipython=8.11.0
  - jasper=2.0.33
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - jupyter_client=8.0.3
  - jupyter_core=4.12.0
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.74.1
  - libiconv=1.17
  - libidn2=2.3.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.46.0
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.8.1
  - networkx=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - opencv=4.7.0
  - openh264=2.3.1
  - openssl=1.1.1t
  - p11-kit=0.24.1
  - packaging=23.0
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - pooch=1.4.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-opencv=4.7.0
  - pycparser=2.21
  - pygments=2.14.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=2.1.0
  - pyzmq=25.0.1
  - readline=8.2
  - requests=2.28.1
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.41.1
  - stack_data=0.6.2
  - svt-av1=1.4.1
  - sympy=1.11.1
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing_extensions=4.4.0
  - unicodedata2=15.0.0
  - urllib3=1.26.14
  - wcwidth=0.2.6
  - wheel=0.38.4
  - x264=1!157.20191217
  - xz=5.2.10
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
prefix: /Users/gordeiussatsov/opt/anaconda3/envs/ageProgression
